### ISSUE TITLE
Add frontend framework

### ISSUE THREAD

**Issue by lucca65** [Cendrao/forum#2]
Include semantic UI in the main views and define a footer and header that will allow

- multiple links
- nested menus
- user section
- search bar

**Comment by Cendrao** [comment]
Well... I really do not know how to start this one....

Does bootstrap count as a good web framework?

**Comment by lucca65** [comment]
nop, looks like a shitty site when it uses bootstrap (:

**Comment by Cendrao** [comment]
I've been looking and I found some interesting projects:

* [Semantic UI](https://semantic-ui.com)
* [Skeleton](http://getskeleton.com)


I really liked Semantic UI it looks like very complete and the default styling it's very nice, it doens't look that need a lot of customizations.

Skeleton looks good because it promises to be lightweight and is just vanilla CSS, but their grid system seems a little messy.

I could mention [Metro UI](https://metroui.org.ua) too, but it is just, too Microsoft (:

And I am really tired of [Material Design](https://material.io/guidelines) too.

I think it will be Semantic UI, what do you think @lucca65 ?

**Comment by lucca65** [comment]
Of all of them, semantic ui is my favorite, i use in my projects always. But I have no objections against neither of the options, your pick!

**Comment by Cendrao** [comment]
Ok! Semantic UI it is!

This is issue is related just to add the framework to the project, don't make any view change yet, right?

**Comment by lucca65** [comment]
Yeah, but do update some stuff to make sure you have its css and js working right. 

This task also includes stuff about web pack or gulp or pure npm, etc... take your time on this

**Comment by Cendrao** [comment]
I am getting some gulp erros when I try to `gulp build` the semantic ui, still trying to figure it out.

Steps for reproduce:
* clone or pull frontend-framework branch
* npm install
* cd semantic
* gulp build

```
'build-javascript' errored after 36 ms
[23:34:12] TypeError: Expected mode to be null/undefined/number/Object
    at module.exports (/Users/cendrao/workspace/elixir/forum/node_modules/gulp-chmod/index.js:30:9)
    at Gulp.module.exports (/Users/cendrao/workspace/elixir/forum/semantic/tasks/build/javascript.js:63:40)
    at module.exports (/Users/cendrao/workspace/elixir/forum/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/cendrao/workspace/elixir/forum/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/cendrao/workspace/elixir/forum/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/cendrao/workspace/elixir/forum/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/cendrao/workspace/elixir/forum/node_modules/run-sequence/index.js:86:16)
    at runSequence (/Users/cendrao/workspace/elixir/forum/node_modules/run-sequence/index.js:97:2)
    at Gulp.module.exports (/Users/cendrao/workspace/elixir/forum/semantic/tasks/build.js:49:3)
    at module.exports (/Users/cendrao/workspace/elixir/forum/node_modules/orchestrator/lib/runTask.js:34:7)
[23:34:12] 'build' errored after 41 ms
[23:34:12] TypeError in plugin 'run-sequence(build-javascript)'
Message:
    Expected mode to be null/undefined/number/Object
Stack:
TypeError: Expected mode to be null/undefined/number/Object
    at module.exports (/Users/cendrao/workspace/elixir/forum/node_modules/gulp-chmod/index.js:30:9)
    at Gulp.module.exports (/Users/cendrao/workspace/elixir/forum/semantic/tasks/build/javascript.js:63:40)
    at module.exports (/Users/cendrao/workspace/elixir/forum/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/cendrao/workspace/elixir/forum/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/cendrao/workspace/elixir/forum/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/cendrao/workspace/elixir/forum/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/cendrao/workspace/elixir/forum/node_modules/run-sequence/index.js:86:16)
    at runSequence (/Users/cendrao/workspace/elixir/forum/node_modules/run-sequence/index.js:97:2)
    at Gulp.module.exports (/Users/cendrao/workspace/elixir/forum/semantic/tasks/build.js:49:3)
    at module.exports (/Users/cendrao/workspace/elixir/forum/node_modules/orchestrator/lib/runTask.js:34:7)
```
